### ISSUE TITLE
modify the UI to use yaml

### ISSUE THREAD

**Issue by rabutler** [BoulderCodeHub/Process-CRSS-Res#54]
use `yaml::yaml.load_files("tst.yml")` instead of providing the UI in the R script

example yaml file:

```
--- # define the CRSS processing for this month's run
start_month: "January"
scenarios:
  - name: "January Official"
    scenarios: ????? [how to specify 35 folders]
    ic:
        powell: 3625
        mead: 1075
    start_year: 2019
    std_ind_plots: TRUE
    shortage_conditions: TRUE
    pe_scatter: TRUE
  - name: August Official
    ic:
        powell: 3627.55
        mead: "C:/alan/mead.csv"
    start_year: 2018
ofolder: "C:/alan"
plot_groups: 
    - "January Official", "August Official"
        end_plot_year: 2060
    - "January Official", "January Stress Test"
        end_plot_year: 2026
   - "August Official", "August Stress Test"
process_data:
    sys_cond_data: TRUE
    pe_data: TRUE
    crss_short_cond_data: FALSE
```

-----------

**need to figure out if we specify some parameters for each figure, or for each plot group; need to think about which result in more copies of the same info.**

- try - each plot group has a list of all the plots to create, and then custom values are specified there. 
- ~alternatively, specify in create_figures - but instead of TRUE/FALSE, each contains multiple entries of scenario groups, and then custom values within that group.~
